version: "3.8"

services:
  elasticsearch:
    build:
      dockerfile: ./docker/Dockerfile.elasticsearch
      context: .
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    profiles:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    profiles:
      - elasticsearch

  opensearch:
    build:
      dockerfile: ./docker/Dockerfile.opensearch
      context: .
    ports:
      - 9201:9200
    environment:
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - os-data:/usr/share/opensearch/data
    profiles:
      - opensearch

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.2.0
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - 5602:5601
    profiles:
      - opensearch


volumes:
  es-data:
  os-data: