
name: CI
on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - "*"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies 💿
        run: yarn install --frozen-lockfile
      - name: Run lint 👮‍
        run: yarn lint
      - name: Run Tests 🧪
        run: yarn coverage
      - name: Report coverage (algolia) 📏
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: ./packages/algolia
          flags: algolia
      - name: Report coverage (elasticsearch) 📏
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: ./packages/elasticsearch
          flags: elasticsearch
      - name: Report coverage (core) 📏
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: ./packages/core
          flags: core

#  Publish:
#    runs-on: ubuntu-latest
#    needs:
#      - Test
#    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta' }}
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: 16.x
#          registry-url: https://registry.npmjs.org
#      - uses: actions/cache@v2
#        with:
#          path: "**/node_modules"
#          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
#      - name: Install dependencies 💿
#        run: yarn install --frozen-lockfile
#      - name: Publish 🚀
#        run: yarn run release
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}